//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustDoorsAndScreens
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoorItem
    {
        public int DoorItemID { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ColorTypeID { get; set; }
        public Nullable<int> LockTypeID { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width1 { get; set; }
        public Nullable<decimal> Width2 { get; set; }
        public Nullable<decimal> Width3 { get; set; }
        public Nullable<bool> SliderTopTrack { get; set; }
        public Nullable<bool> SliderBottomTrack { get; set; }
        public Nullable<bool> SliderSideChannel { get; set; }
        public Nullable<bool> SliderFs { get; set; }
        public Nullable<bool> SliderZs { get; set; }
        public Nullable<bool> SliderBugStrip { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> DoorTypeID { get; set; }
        public Nullable<int> DesignTypeID { get; set; }
        public Nullable<decimal> LockHeight { get; set; }
        public Nullable<decimal> SliderTopTrackWidth { get; set; }
        public Nullable<decimal> SliderBottomTrackWidth { get; set; }
        public Nullable<decimal> SliderSideChannelWidth { get; set; }
        public string TrackTypes { get; set; }
        public Nullable<int> SliderTopTrackType { get; set; }
        public Nullable<int> SliderBottomTrackType { get; set; }
        public Nullable<int> SliderSideChannelType { get; set; }
        public Nullable<int> F { get; set; }
        public Nullable<int> Z { get; set; }
        public Nullable<int> HingeType { get; set; }
        public Nullable<int> BugStrip { get; set; }
    
        public virtual ColorType ColorType { get; set; }
        public virtual DesignType DesignType { get; set; }
        public virtual DoorType DoorType { get; set; }
        public virtual LockType LockType { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual HingeType HingeType1 { get; set; }
        public virtual TrackType TrackType { get; set; }
        public virtual TrackType TrackType1 { get; set; }
        public virtual TrackType TrackType2 { get; set; }
    }
}
