//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustDoorsAndScreens
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FlyScreenItem
    {
        public int FlyScreenItemsID { get; set; }
        public Nullable<int> QuoteID { get; set; }
        [Required]
        public Nullable<int> FlyScreenTypeID { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> Qty { get; set; }
        [Required]
        public Nullable<decimal> Cost { get; set; }
        [Required]
        public Nullable<int> ColorTypeID { get; set; }
        public Nullable<decimal> W1 { get; set; }
        public Nullable<decimal> D1 { get; set; }
        public Nullable<int> Q1 { get; set; }
        public Nullable<decimal> W2 { get; set; }
        public Nullable<decimal> D2 { get; set; }
        public Nullable<int> Q2 { get; set; }
        public Nullable<decimal> W3 { get; set; }
        public Nullable<decimal> D3 { get; set; }
        public Nullable<int> Q3 { get; set; }
        public Nullable<decimal> W4 { get; set; }
        public Nullable<decimal> D4 { get; set; }
        public Nullable<int> Q4 { get; set; }
        public Nullable<decimal> W5 { get; set; }
        public Nullable<decimal> D5 { get; set; }
        public Nullable<int> Q5 { get; set; }
        public Nullable<decimal> W6 { get; set; }
        public Nullable<decimal> D6 { get; set; }
        public Nullable<int> Q6 { get; set; }
        public Nullable<decimal> W7 { get; set; }
        public Nullable<decimal> D7 { get; set; }
        public Nullable<int> Q7 { get; set; }
        public Nullable<decimal> W8 { get; set; }
        public Nullable<decimal> D8 { get; set; }
        public Nullable<int> Q8 { get; set; }
        public Nullable<decimal> W9 { get; set; }
        public Nullable<decimal> D9 { get; set; }
        public Nullable<int> Q9 { get; set; }
        public Nullable<decimal> W10 { get; set; }
        public Nullable<decimal> D10 { get; set; }
        public Nullable<int> Q10 { get; set; }
        public Nullable<decimal> W11 { get; set; }
        public Nullable<decimal> D11 { get; set; }
        public Nullable<int> Q11 { get; set; }
        public Nullable<decimal> W12 { get; set; }
        public Nullable<decimal> D12 { get; set; }
        public Nullable<int> Q12 { get; set; }
        public Nullable<decimal> W13 { get; set; }
        public Nullable<decimal> D13 { get; set; }
        public Nullable<int> Q13 { get; set; }
        public Nullable<decimal> W14 { get; set; }
        public Nullable<decimal> D14 { get; set; }
        public Nullable<int> Q14 { get; set; }
        public Nullable<decimal> W15 { get; set; }
        public Nullable<decimal> D15 { get; set; }
        public Nullable<int> Q15 { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Required { get; set; }

        public virtual FlysScreenType FlysScreenType { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual ColorType ColorType { get; set; }
    }
}
