//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustDoorsAndScreens
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyScreenItem
    {
        public int FlyScreenItemsID { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<int> FlyScreenTypeID { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> ColorTypeID { get; set; }
    
        public virtual FlysScreenType FlysScreenType { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual ColorType ColorType { get; set; }
    }
}
