//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustDoorsAndScreens
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlysScreenType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlysScreenType()
        {
            this.FlyScreenItems = new HashSet<FlyScreenItem>();
        }
    
        public int FlyScreenTypeID { get; set; }
        public string FlyScreenName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlyScreenItem> FlyScreenItems { get; set; }
    }
}
