//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustDoorsAndScreens
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JustDoorsAndScreensEntities : DbContext
    {
        public JustDoorsAndScreensEntities()
            : base("name=JustDoorsAndScreensEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ColorType> ColorTypes { get; set; }
        public virtual DbSet<DesignType> DesignTypes { get; set; }
        public virtual DbSet<DoorType> DoorTypes { get; set; }
        public virtual DbSet<FlysScreenType> FlysScreenTypes { get; set; }
        public virtual DbSet<LockType> LockTypes { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<StagesType> StagesTypes { get; set; }
        public virtual DbSet<DoorItem> DoorItems { get; set; }
        public virtual DbSet<FlyScreenItem> FlyScreenItems { get; set; }
        public virtual DbSet<vwFlyScreenItem> vwFlyScreenItems { get; set; }
        public virtual DbSet<vwQuoteReport> vwQuoteReports { get; set; }
        public virtual DbSet<vwRolledQuoteCost> vwRolledQuoteCosts { get; set; }
        public virtual DbSet<TrackType> TrackTypes { get; set; }
        public virtual DbSet<HingeType> HingeTypes { get; set; }
        public virtual DbSet<vwDoorItem> vwDoorItems { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
