//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustDoorsAndScreens
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDoorItem
    {
        public int id { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public string Description { get; set; }
        public string DoorTypeName { get; set; }
        public string DesignTypeName { get; set; }
        public string ColorTypeName { get; set; }
        public string LockTypeName { get; set; }
        public Nullable<decimal> LockHeight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width1 { get; set; }
        public Nullable<decimal> Width2 { get; set; }
        public Nullable<decimal> Width3 { get; set; }
        public string HingeTypeName { get; set; }
        public Nullable<bool> SliderTopTrack { get; set; }
        public string SliderTopTrackTypeName { get; set; }
        public Nullable<decimal> SliderTopTrackWidth { get; set; }
        public Nullable<bool> SliderBottomTrack { get; set; }
        public string SliderBottomTrackTypeName { get; set; }
        public Nullable<decimal> SliderBottomTrackWidth { get; set; }
        public Nullable<bool> SliderSideChannel { get; set; }
        public string SliderSideChannelTypeName { get; set; }
        public Nullable<decimal> SliderSideChannelWidth { get; set; }
        public Nullable<bool> SliderFs { get; set; }
        public Nullable<bool> SliderZs { get; set; }
        public Nullable<bool> SliderBugStrip { get; set; }
        public string TrackTypes { get; set; }
        public Nullable<int> F { get; set; }
        public Nullable<int> Z { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> BugStrip { get; set; }
    }
}
