//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustDoorsAndScreens
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFlyScreenItem
    {
        public int id { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public string FlyScreenName { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string ColorTypeName { get; set; }
    }
}
