//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustDoorsAndScreens
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwQuoteReport
    {
        public int QuoteID { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Stage { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
    }
}
