//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustDoorsAndScreens
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRolledQuoteCost
    {
        public Nullable<int> QuoteID { get; set; }
        public string Item { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
